# Generated by Django 5.2.4 on 2026-01-02 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstore', '0002_add_phone2_email_to_booksupplier'),
        ('students', '0002_student_unpaid_amount'),
        ('teachers', '0021_alter_salary_month_alter_salary_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_number', models.CharField(max_length=50, verbose_name='문제 번호')),
                ('problem_type', models.CharField(choices=[('concept', '개념'), ('basic', '기본'), ('practice', '연습'), ('advanced', '심화'), ('review', '복습'), ('test', '테스트')], default='basic', max_length=20, verbose_name='문제 유형')),
                ('chapter', models.CharField(blank=True, max_length=100, verbose_name='단원/챕터')),
                ('page', models.PositiveIntegerField(blank=True, null=True, verbose_name='페이지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='비고')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='bookstore.book', verbose_name='교재')),
            ],
            options={
                'verbose_name': '교재 문제',
                'verbose_name_plural': '교재 문제 목록',
                'ordering': ['book', 'order', 'problem_number'],
                'unique_together': {('book', 'problem_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='bookstore.book', verbose_name='교재')),
                ('book_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='bookstore.booksale', verbose_name='교재 판매 내역')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_sheets', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '학생 진도표',
                'verbose_name_plural': '학생 진도표 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assigned', models.BooleanField(default=False, verbose_name='과제 체크')),
                ('study_date', models.DateField(blank=True, null=True, verbose_name='학습 날짜')),
                ('understanding', models.PositiveIntegerField(blank=True, choices=[(1, '매우 부족'), (2, '부족'), (3, '보통'), (4, '양호'), (5, '완벽')], null=True, verbose_name='이해 정도')),
                ('homework', models.CharField(blank=True, max_length=255, verbose_name='과제')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='비고')),
                ('book_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.bookproblem', verbose_name='문제')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='담당 선생님')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='progress.studentprogress', verbose_name='진도표')),
            ],
            options={
                'verbose_name': '진도 항목',
                'verbose_name_plural': '진도 항목 목록',
                'ordering': ['progress', 'book_problem__order', 'book_problem__problem_number'],
                'unique_together': {('progress', 'book_problem')},
            },
        ),
    ]
