# Generated by Django 5.2.4 on 2026-01-02 02:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_add_phone2_email_to_booksupplier'),
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.CharField(help_text='형식: [과목코드4자리][대단원2자리][중단원2자리][소단원2자리][유형3자리][문제번호4자리][난도2자리]', max_length=19, unique=True, validators=[django.core.validators.RegexValidator(message='코드 번호는 정확히 19자리 숫자여야 합니다.', regex='^\\d{19}$')], verbose_name='코드 번호')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '문제 유형',
                'verbose_name_plural': '문제 유형 목록',
                'ordering': ['code_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='bookproblem',
            options={'ordering': ['book', 'order'], 'verbose_name': '교재 문제', 'verbose_name_plural': '교재 문제 목록'},
        ),
        migrations.AlterModelOptions(
            name='progressentry',
            options={'ordering': ['progress', 'book_problem__order'], 'verbose_name': '진도 항목', 'verbose_name_plural': '진도 항목 목록'},
        ),
        migrations.AlterUniqueTogether(
            name='bookproblem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bookproblem',
            name='problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_problems', to='progress.problemtype', verbose_name='문제 유형'),
        ),
        migrations.AlterUniqueTogether(
            name='bookproblem',
            unique_together={('book', 'problem_type')},
        ),
        migrations.RemoveField(
            model_name='bookproblem',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='bookproblem',
            name='problem_number',
        ),
    ]
