# Generated by Django 5.2.4 on 2026-01-04 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_problemtype_alter_bookproblem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtype',
            name='difficulty',
            field=models.PositiveIntegerField(default=5, help_text='1(쉬움) ~ 10(어려움)', validators=[django.core.validators.MinValueValidator(1, message='난도는 1 이상이어야 합니다.'), django.core.validators.MaxValueValidator(10, message='난도는 10 이하여야 합니다.')], verbose_name='난도'),
        ),
        migrations.AlterField(
            model_name='problemtype',
            name='code_number',
            field=models.CharField(help_text='형식: [과목코드4자리][대단원2자리][중단원2자리][소단원2자리][유형3자리][문제번호4자리]', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='코드 번호는 정확히 17자리 숫자여야 합니다.', regex='^\\d{17}$')], verbose_name='코드 번호'),
        ),
    ]
