# Generated by Django 5.2.4 on 2026-01-04 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_separate_difficulty_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtype',
            name='code_number',
            field=models.CharField(help_text='형식: [교재코드7자리][대단원2자리][중단원2자리][소단원2자리][유형3자리][문제번호4자리]', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='코드 번호는 정확히 20자리 숫자여야 합니다.', regex='^\\d{20}$')], verbose_name='코드 번호'),
        ),
    ]
