# Generated by Django 5.2.4 on 2026-02-07 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_update_code_number_to_20_digits'),
        ('students', '0003_student_director_memo'),
        ('subjects', '0002_subject_category_code'),
        ('teachers', '0033_alter_salary_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='활동 날짜')),
                ('activity_type', models.CharField(choices=[('print', '프린트'), ('worksheet', '학습지'), ('lecture', '강의'), ('discussion', '토론'), ('practice', '연습문제'), ('review', '복습'), ('other', '기타')], default='print', max_length=20, verbose_name='활동 유형')),
                ('title', models.CharField(max_length=200, verbose_name='활동명')),
                ('achievement', models.CharField(blank=True, choices=[('A', '매우 우수'), ('B', '우수'), ('C', '보통'), ('D', '미흡'), ('F', '매우 미흡')], max_length=1, verbose_name='성취도')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='점수')),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='만점')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.student', verbose_name='학생')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject', verbose_name='과목')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_activities', to='teachers.teacher', verbose_name='담당 교사')),
            ],
            options={
                'verbose_name': '수업 활동',
                'verbose_name_plural': '수업 활동 목록',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'date'], name='progress_st_student_1a28ad_idx'), models.Index(fields=['date'], name='progress_st_date_9a5f93_idx')],
            },
        ),
    ]
