# Generated by Django 5.2.4 on 2026-02-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_add_student_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='needs_review',
            field=models.BooleanField(default=False, verbose_name='보완 필요'),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='activity_type',
            field=models.CharField(choices=[('print', '프린트'), ('practice', '연습문제'), ('quiz', '퀴즈'), ('review', '복습'), ('homework_check', '과제 확인'), ('other', '기타')], default='print', max_length=20, verbose_name='활동 유형'),
        ),
    ]
