# Generated by Django 5.2.4 on 2026-02-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_add_needs_review_and_update_activity_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentactivity',
            name='homework_checked',
            field=models.BooleanField(default=False, verbose_name='과제 확인'),
        ),
        migrations.AlterField(
            model_name='studentactivity',
            name='activity_type',
            field=models.CharField(choices=[('quiz', '퀴즈'), ('practice', '추가 연습 문제'), ('booklet', '제본 교재'), ('other', '기타')], default='print', max_length=20, verbose_name='활동 유형'),
        ),
    ]
