# Generated by Django 5.2.4 on 2026-02-09 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_add_student_book_progress'),
        ('progress', '0007_update_activity_types_add_homework_checked'),
        ('students', '0003_student_director_memo'),
        ('subjects', '0002_subject_category_code'),
        ('teachers', '0033_alter_salary_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('textbook', '교재 진도'), ('quiz', '퀴즈'), ('practice', '추가 연습 문제'), ('booklet', '제본 교재'), ('other', '기타')], default='textbook', max_length=20, verbose_name='기록 유형')),
                ('date', models.DateField(verbose_name='학습 날짜')),
                ('title', models.CharField(max_length=200, verbose_name='학습 내용')),
                ('achievement', models.CharField(blank=True, choices=[('', '-'), ('A', 'A (우수)'), ('B', 'B (양호)'), ('C', 'C (보통)'), ('D', 'D (미흡)'), ('F', 'F (재학습)')], default='', max_length=1, verbose_name='성취도')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='점수')),
                ('total_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='만점')),
                ('homework_checked', models.BooleanField(default=False, verbose_name='과제 확인')),
                ('needs_review', models.BooleanField(default=False, verbose_name='보완 필요')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('book_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='bookstore.bookcontent', verbose_name='목차 항목')),
                ('book_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='bookstore.booksale', verbose_name='교재 지급')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='students.student', verbose_name='학생')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject', verbose_name='과목')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_records', to='teachers.teacher', verbose_name='담당 교사')),
            ],
            options={
                'verbose_name': '학습 기록',
                'verbose_name_plural': '학습 기록 목록',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'date'], name='progress_le_student_884e03_idx'), models.Index(fields=['date'], name='progress_le_date_20e640_idx'), models.Index(fields=['record_type'], name='progress_le_record__5a4061_idx'), models.Index(fields=['book_sale'], name='progress_le_book_sa_137358_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('record_type', 'textbook')), fields=('book_sale', 'book_content'), name='unique_textbook_progress')],
            },
        ),
    ]
