# Generated by Django 5.2.4 on 2026-02-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_migrate_data_to_learning_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecord',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='학습 날짜'),
        ),
    ]
