# Generated by Django 5.2.4 on 2026-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0011_migrate_pending_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecord',
            name='record_type',
            field=models.CharField(choices=[('textbook', '교재 진도'), ('quiz', '퀴즈'), ('practice', '추가 연습 문제'), ('booklet', '제본 교재'), ('entrance_exam', '입학 시험'), ('other', '기타')], default='textbook', max_length=20, verbose_name='기록 유형'),
        ),
    ]
