# Generated by Django 5.2.4 on 2026-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0014_move_quiz_results_to_learningrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningrecord',
            name='homework_completed',
            field=models.BooleanField(default=False, verbose_name='과제 이행'),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='homework_checked',
            field=models.BooleanField(default=False, verbose_name='과제 부과'),
        ),
    ]
