# Generated by Django 5.1.4 on 2024-12-08 23:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_purchaselocation_business_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('grade', models.CharField(blank=True, choices=[('K5', 'K5'), ('K6', 'K6'), ('K7', 'K7'), ('K8', 'K8'), ('K9', 'K9'), ('K10', 'K10'), ('K11', 'K11'), ('K12', 'K12')], max_length=3, null=True, verbose_name='학년')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='형식: 000-0000-0000', regex='^\\d{3}-\\d{3,4}-\\d{4}$')], verbose_name='학생 전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일 주소')),
                ('gender', models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, null=True, verbose_name='성별')),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='형식: 000-0000-0000', regex='^\\d{3}-\\d{3,4}-\\d{4}$')], verbose_name='부모님 전화번호')),
                ('receipt_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='현금영수증용 번호')),
                ('interview_date', models.DateField(blank=True, null=True, verbose_name='인터뷰 날짜')),
                ('interview_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='인터뷰 기본 성적')),
                ('interview_info', models.TextField(blank=True, null=True, verbose_name='인터뷰 정보')),
                ('first_class_date', models.DateField(blank=True, null=True, verbose_name='첫수업 날짜')),
                ('quit_date', models.DateField(blank=True, null=True, verbose_name='그만 둔 날짜')),
                ('student_id', models.CharField(max_length=8, unique=True, verbose_name='고유번호')),
                ('personal_file', models.FileField(blank=True, null=True, upload_to='student_files/', verbose_name='개인 파일')),
                ('etc', models.TextField(blank=True, null=True, verbose_name='기타')),
                ('extra1', models.CharField(blank=True, max_length=100, null=True, verbose_name='예비1')),
                ('extra2', models.CharField(blank=True, max_length=100, null=True, verbose_name='예비2')),
                ('extra3', models.CharField(blank=True, max_length=100, null=True, verbose_name='예비3')),
                ('extra4', models.CharField(blank=True, max_length=100, null=True, verbose_name='예비4')),
                ('extra5', models.CharField(blank=True, max_length=100, null=True, verbose_name='예비5')),
                ('is_active', models.BooleanField(default=True, verbose_name='활동 여부')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.school', verbose_name='학교')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생',
            },
        ),
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_files/', verbose_name='파일')),
                ('file_name', models.CharField(max_length=255, verbose_name='파일명')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 날짜')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='students.student')),
            ],
            options={
                'verbose_name': '학생 파일',
                'verbose_name_plural': '학생 파일',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
