# Generated by Django 5.2.4 on 2025-12-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='unpaid_amount',
            field=models.IntegerField(default=0, verbose_name='미납 수업료'),
        ),
    ]
