# Generated by Django 5.2.4 on 2026-01-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_unpaid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='director_memo',
            field=models.TextField(blank=True, help_text='학생 특징 및 요구사항 (선생님에게 표시됨)', null=True, verbose_name='원장 메모'),
        ),
    ]
