# Generated by Django 5.2.4 on 2026-03-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_director_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hs_admission_year',
            field=models.IntegerField(blank=True, help_text='2025년 이후 입학 → 2022 개정교육과정. 2024년 이전 → 2015 교육과정', null=True, verbose_name='고등학교 입학년도'),
        ),
    ]
