# Generated by Django 5.2.4 on 2026-07-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_hs_admission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='구글 드라이브 폴더 ID'),
        ),
    ]
