# Generated by Django 5.2.4 on 2026-03-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstore', '0010_add_is_learning_completed_to_booksale'),
        ('students', '0004_add_hs_admission_year'),
        ('subjects', '0004_subject_school_level'),
        ('teachers', '0035_alter_salary_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='수업 이름')),
                ('mon', models.BooleanField(default=False, verbose_name='월')),
                ('tue', models.BooleanField(default=False, verbose_name='화')),
                ('wed', models.BooleanField(default=False, verbose_name='수')),
                ('thu', models.BooleanField(default=False, verbose_name='목')),
                ('fri', models.BooleanField(default=False, verbose_name='금')),
                ('sat', models.BooleanField(default=False, verbose_name='토')),
                ('sun', models.BooleanField(default=False, verbose_name='일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('base_tuition', models.PositiveIntegerField(verbose_name='기본 수강료')),
                ('memo', models.TextField(blank=True, verbose_name='기타')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('books', models.ManyToManyField(blank=True, to='bookstore.book', verbose_name='교재')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject', verbose_name='과목')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='담당 교사')),
            ],
            options={
                'verbose_name': '수업',
                'verbose_name_plural': '수업 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(verbose_name='수강 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='수강 종료일')),
                ('tuition_adjustment', models.IntegerField(default=0, verbose_name='수강료 조정액')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='학생')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='classes.lesson', verbose_name='수업')),
            ],
            options={
                'verbose_name': '수강 신청',
                'verbose_name_plural': '수강 신청 목록',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='납부 연도')),
                ('month', models.IntegerField(choices=[(1, '1월'), (2, '2월'), (3, '3월'), (4, '4월'), (5, '5월'), (6, '6월'), (7, '7월'), (8, '8월'), (9, '9월'), (10, '10월'), (11, '11월'), (12, '12월')], verbose_name='납부 월')),
                ('amount', models.PositiveIntegerField(verbose_name='납부 금액')),
                ('payment_date', models.DateField(verbose_name='납부일')),
                ('payment_method', models.CharField(choices=[('cash', '현금'), ('card', '카드'), ('transfer', '계좌이체'), ('other', '기타')], max_length=20, verbose_name='납부 방법')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='classes.enrollment', verbose_name='수강 신청')),
            ],
            options={
                'verbose_name': '수강료 납부',
                'verbose_name_plural': '수강료 납부 목록',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
