# Generated by Django 5.2.4 on 2026-03-26 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0035_alter_salary_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='fri',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='thu',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='tue',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='wed',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='담당 선생님'),
        ),
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', '월'), ('tue', '화'), ('wed', '수'), ('thu', '목'), ('fri', '금'), ('sat', '토'), ('sun', '일')], max_length=3, verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.lesson', verbose_name='수업')),
            ],
            options={
                'verbose_name': '수업 일정',
                'verbose_name_plural': '수업 일정 목록',
                'unique_together': {('lesson', 'day')},
            },
        ),
    ]
