# Generated by Django 5.2.4 on 2026-04-01 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_lesson_end_time_remove_lesson_fri_and_more'),
        ('students', '0004_add_hs_admission_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionpayment',
            name='payment_method',
            field=models.CharField(choices=[('kjt', '결제선생'), ('daon', '다온카드'), ('card', '신용카드'), ('transfer', '계좌이체'), ('cash', '현금'), ('other', '기타')], max_length=20, verbose_name='납부 방법'),
        ),
        migrations.CreateModel(
            name='MonthlyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('month', models.IntegerField(choices=[(1, '1월'), (2, '2월'), (3, '3월'), (4, '4월'), (5, '5월'), (6, '6월'), (7, '7월'), (8, '8월'), (9, '9월'), (10, '10월'), (11, '11월'), (12, '12월')], verbose_name='월')),
                ('status', models.CharField(choices=[('pending', '신청 중'), ('confirmed', '확정'), ('cancelled', '취소')], default='pending', max_length=10, verbose_name='상태')),
                ('tuition_adjustment', models.IntegerField(default=0, verbose_name='수강료 조정액')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_enrollments', to='classes.lesson', verbose_name='수업')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_enrollments', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '월별 수강 신청',
                'verbose_name_plural': '월별 수강 신청 목록',
                'ordering': ['year', 'month', 'lesson__name', 'student__name'],
                'unique_together': {('student', 'year', 'month', 'lesson')},
            },
        ),
    ]
