# Generated by Django 5.2.4 on 2026-04-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_tuitionpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyenrollment',
            name='tuition_fee',
            field=models.PositiveIntegerField(null=True, verbose_name='수강료'),
        ),
    ]
