# Generated by Django 5.2.4 on 2026-05-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_populate_tuition_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='특별 수업'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
    ]
