# Generated by Django 5.2.4 on 2026-05-31 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_special_lesson_fields'),
        ('students', '0004_add_hs_admission_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quit_date', models.DateField(verbose_name='퇴원일')),
                ('year', models.IntegerField(verbose_name='환불 연도')),
                ('month', models.IntegerField(choices=[(1, '1월'), (2, '2월'), (3, '3월'), (4, '4월'), (5, '5월'), (6, '6월'), (7, '7월'), (8, '8월'), (9, '9월'), (10, '10월'), (11, '11월'), (12, '12월')], verbose_name='환불 월')),
                ('tuition', models.PositiveIntegerField(verbose_name='월 수강료')),
                ('total_days', models.PositiveIntegerField(verbose_name='총 수업일수')),
                ('passed_days', models.PositiveIntegerField(verbose_name='수강 일수')),
                ('refund_rate', models.PositiveIntegerField(verbose_name='환불율(%)')),
                ('refund_amount', models.PositiveIntegerField(verbose_name='환불 금액')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='classes.enrollment', verbose_name='수강 신청')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '수강료 환불',
                'verbose_name_plural': '수강료 환불 목록',
                'ordering': ['-quit_date', '-created_at'],
            },
        ),
    ]
