# Generated by Django 5.2.4 on 2025-12-24 01:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='납부 금액')),
                ('status', models.CharField(blank=True, choices=[('pending', '미납'), ('partial', '부분납부'), ('completed', '완납'), ('refunded', '환불됨')], default='pending', max_length=10, null=True, verbose_name='납부 상태')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '현금'), ('card', '카드'), ('transfer', '계좌이체'), ('other', '기타')], max_length=10, null=True, verbose_name='결제 수단')),
                ('payment_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='결제일')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제 내역',
                'ordering': ['-payment_date', 'student__name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='결제 금액')),
                ('payment_method', models.CharField(choices=[('cash', '현금'), ('card', '카드'), ('transfer', '계좌이체'), ('other', '기타')], max_length=10, verbose_name='결제 수단')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='결제 시각')),
                ('receipt_no', models.CharField(blank=True, max_length=50, verbose_name='영수증 번호')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='payment.payment', verbose_name='결제')),
            ],
            options={
                'verbose_name': '결제 이력',
                'verbose_name_plural': '결제 이력 목록',
                'ordering': ['-paid_at'],
            },
        ),
    ]
