# Generated by Django 5.1.4 on 2024-12-20 01:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_options_remove_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='결제일'),
        ),
    ]
