# Generated by Django 5.1.4 on 2024-12-20 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', 'student__name'], 'verbose_name': '결제', 'verbose_name_plural': '결제 내역'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='결제일'),
        ),
    ]
