# Generated by Django 5.1 on 2024-10-29 00:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_alter_purchaselocation_business_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='교재 이름')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='입고일')),
                ('original_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='원가')),
                ('purchase_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='입고 가격')),
                ('selling_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='판매 가격')),
                ('difficulty_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='교재 난이도')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('spare1', models.CharField(blank=True, max_length=200, null=True, verbose_name='예비1')),
                ('spare2', models.CharField(blank=True, max_length=200, null=True, verbose_name='예비2')),
                ('spare3', models.CharField(blank=True, max_length=200, null=True, verbose_name='예비3')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.publisher', verbose_name='출판사')),
                ('purchase_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.purchaselocation', verbose_name='구입처')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '교재',
                'verbose_name_plural': '교재 목록',
            },
        ),
    ]
