# Generated by Django 5.1 on 2024-10-29 03:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('common', '0002_alter_purchaselocation_business_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='구입처명')),
            ],
            options={
                'verbose_name': '구입처',
                'verbose_name_plural': '구입처 목록',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='spare1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='spare2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='spare3',
        ),
        migrations.AddField(
            model_name='book',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='바코드'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='qr_code',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True, verbose_name='QR코드'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='purchase_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.purchaselocation', verbose_name='구입처'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name', 'isbn'], name='books_book_name_01857d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['barcode'], name='books_book_barcode_aa9bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['qr_code'], name='books_book_qr_code_5dacf9_idx'),
        ),
    ]
