# Generated by Django 5.1 on 2024-10-29 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_purchaselocation_remove_book_spare1_and_more'),
        ('common', '0002_alter_purchaselocation_business_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='purchase_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.purchaselocation', verbose_name='구입처'),
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_name_01857d_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_barcode_aa9bc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='books_book_qr_code_5dacf9_idx',
        ),
        migrations.RemoveField(
            model_name='book',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='book',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='book',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='book',
            name='spare1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='예비1'),
        ),
        migrations.AddField(
            model_name='book',
            name='spare2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='예비2'),
        ),
        migrations.AddField(
            model_name='book',
            name='spare3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='예비3'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.DeleteModel(
            name='PurchaseLocation',
        ),
    ]
