# Generated by Django 5.1 on 2024-10-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_purchase_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='books/barcodes/', verbose_name='바코드'),
        ),
        migrations.AddField(
            model_name='book',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='books/qrcodes/', verbose_name='QR코드'),
        ),
        migrations.AddField(
            model_name='book',
            name='unique_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='고유코드'),
        ),
    ]
