# Generated by Django 5.1 on 2024-10-29 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_barcode_book_qr_code_book_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='books/qrcodes/', verbose_name='QR 코드'),
        ),
        migrations.AlterField(
            model_name='book',
            name='unique_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True, verbose_name='고유 코드'),
        ),
    ]
