# Generated by Django 5.1 on 2024-10-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_qr_code_alter_book_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='selling_price',
        ),
    ]
