# Generated by Django 5.1 on 2024-10-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_original_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='purchase_location',
        ),
    ]
