# Generated by Django 5.1 on 2024-10-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='은행명')),
            ],
            options={
                'verbose_name': '은행',
                'verbose_name_plural': '은행',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='출판사명')),
            ],
            options={
                'verbose_name': '출판사',
                'verbose_name_plural': '출판사',
            },
        ),
        migrations.CreateModel(
            name='PurchaseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='구입처명')),
                ('phone1', models.CharField(max_length=15, verbose_name='전화번호1')),
                ('phone2', models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호2')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일 주소')),
                ('business_number', models.CharField(max_length=20, verbose_name='사업자 번호')),
            ],
            options={
                'verbose_name': '교재 구입처',
                'verbose_name_plural': '교재 구입처',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='교명')),
                ('phone', models.CharField(max_length=15, verbose_name='전화번호')),
                ('address', models.TextField(verbose_name='주소')),
            ],
            options={
                'verbose_name': '학교',
                'verbose_name_plural': '학교',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='과목명')),
            ],
            options={
                'verbose_name': '과목',
                'verbose_name_plural': '과목',
            },
        ),
    ]
