# Generated by Django 5.1 on 2024-10-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselocation',
            name='business_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='사업자 번호'),
        ),
        migrations.AlterField(
            model_name='purchaselocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일 주소'),
        ),
        migrations.AlterField(
            model_name='purchaselocation',
            name='phone1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호1'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호'),
        ),
    ]
