# Generated by Django 5.2.4 on 2026-01-02 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_purchaselocation_business_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseLocation',
        ),
    ]
