# Generated by Django 5.2.4 on 2025-12-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_student_unpaid_amount'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('internal', '내신'), ('mock', '모의고사')], max_length=10, verbose_name='성적 유형')),
                ('year', models.IntegerField(verbose_name='학년')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='원점수')),
                ('subject_average', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='과목 평균')),
                ('subject_stddev', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='과목 표준편차')),
                ('grade_rank', models.IntegerField(choices=[(1, '1등급'), (2, '2등급'), (3, '3등급'), (4, '4등급'), (5, '5등급'), (6, '6등급'), (7, '7등급'), (8, '8등급'), (9, '9등급')], verbose_name='등급')),
                ('semester', models.IntegerField(blank=True, choices=[(1, '1학기'), (2, '2학기')], null=True, verbose_name='학기')),
                ('credits', models.IntegerField(blank=True, null=True, verbose_name='단위')),
                ('is_elective', models.BooleanField(default=False, verbose_name='진로선택 과목 여부')),
                ('exam_year', models.IntegerField(blank=True, null=True, verbose_name='시험 연도')),
                ('exam_month', models.IntegerField(blank=True, null=True, verbose_name='시험 월')),
                ('exam_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='모의고사 이름')),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='백분위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='학생')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '성적',
                'verbose_name_plural': '성적 목록',
                'db_table': 'grades',
                'ordering': ['-year', '-semester', '-exam_year', '-exam_month'],
                'indexes': [models.Index(fields=['student', 'grade_type'], name='grades_student_03b05e_idx'), models.Index(fields=['student', 'year'], name='grades_student_2ab3e0_idx')],
            },
        ),
    ]
