# Generated by Django 5.2.4 on 2025-12-30 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_credits_alter_grade_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='achievement_level',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True, verbose_name='성취도'),
        ),
        migrations.AddField(
            model_name='grade',
            name='distribution_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='성취도 A 비율'),
        ),
        migrations.AddField(
            model_name='grade',
            name='distribution_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='성취도 B 비율'),
        ),
        migrations.AddField(
            model_name='grade',
            name='distribution_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='성취도 C 비율'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_rank',
            field=models.IntegerField(blank=True, choices=[(1, '1등급'), (2, '2등급'), (3, '3등급'), (4, '4등급'), (5, '5등급'), (6, '6등급'), (7, '7등급'), (8, '8등급'), (9, '9등급')], null=True, verbose_name='등급'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='과목 표준편차'),
        ),
    ]
