# Generated by Django 5.2.4 on 2026-03-20 00:39

from django.db import migrations, models


def populate_subject_classification(apps, schema_editor):
    """기존 is_elective 값을 subject_classification으로 마이그레이션"""
    Grade = apps.get_model('grades', 'Grade')
    Grade.objects.filter(is_elective=True).update(subject_classification='elective')
    Grade.objects.filter(is_elective=False).update(subject_classification='general')


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_grade_achievement_level_grade_distribution_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='subject_classification',
            field=models.CharField(choices=[('common', '공통과목'), ('general', '일반선택'), ('elective', '진로선택'), ('fusion', '융합선택')], default='general', help_text='공통과목 / 일반선택 / 진로선택 / 융합선택', max_length=10, verbose_name='과목 분류'),
        ),
        migrations.RunPython(populate_subject_classification, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='grade',
            name='is_elective',
            field=models.BooleanField(default=False, verbose_name='진로선택 과목 여부 (deprecated)'),
        ),
    ]
