# Generated by Django 5.2.4 on 2026-03-20 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_add_subject_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='enrolled_count',
            field=models.IntegerField(blank=True, help_text='과목 수강 인원 (2022 교육과정에서 필요)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='수강자 수'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='achievement_level',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True, verbose_name='성취도'),
        ),
    ]
