# Generated by Django 5.2.4 on 2026-03-20 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_add_enrolled_count_extend_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='same_rank_count',
            field=models.IntegerField(blank=True, help_text='동석차 인원 수 (2022 교육과정)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='동석차 수'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject_rank',
            field=models.IntegerField(blank=True, help_text='과목 석차 (2022 교육과정)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='석차'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject_average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='과목 평균'),
        ),
    ]
