# Generated by Django 5.2.4 on 2025-12-24 03:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='교재명')),
                ('isbn', models.CharField(max_length=50, unique=True, verbose_name='바코드(ISBN)')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='저자')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='출판사')),
                ('original_price', models.PositiveIntegerField(default=0, verbose_name='정상 가격')),
                ('cost_price', models.PositiveIntegerField(default=0, verbose_name='입고 가격')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='판매 가격')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='재고 수량')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일(입고일)')),
            ],
            options={
                'verbose_name': '교재',
                'verbose_name_plural': '교재 목록',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상호명(법인명)')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='사업자 등록번호')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='은행명')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='계좌번호')),
                ('account_owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='예금주')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '구매처',
                'verbose_name_plural': '구매처 목록',
            },
        ),
        migrations.CreateModel(
            name='BookSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='판매일(지급일)')),
                ('price', models.PositiveIntegerField(verbose_name='판매 당시 가격')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('is_paid', models.BooleanField(default=False, verbose_name='결제 완료 여부')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='결제일')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='비고')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='bookstore.book', verbose_name='교재')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_sales', to='students.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '교재 판매 내역',
                'verbose_name_plural': '교재 판매 내역',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='BookStockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량 (입고/반품)')),
                ('cost_price', models.PositiveIntegerField(verbose_name='단가')),
                ('total_payment', models.PositiveIntegerField(default=0, verbose_name='총액')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='날짜')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='입고/반품일')),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='비고')),
                ('is_paid', models.BooleanField(default=False, verbose_name='정산 완료 여부')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='bookstore.book', verbose_name='교재')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.booksupplier', verbose_name='구매처')),
            ],
            options={
                'verbose_name': '재고 기록',
                'verbose_name_plural': '재고 기록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.booksupplier', verbose_name='주거래 구매처'),
        ),
    ]
