# Generated by Django 5.1.4 on 2024-12-08 23:03

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateField(default=django.utils.timezone.now, verbose_name='판매일')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='판매 수량')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '도서 판매',
                'verbose_name_plural': '도서 판매',
                'ordering': ['-sold_date', 'book_stock__book__name'],
            },
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('issued_date', models.DateField(default=django.utils.timezone.now, verbose_name='출고일')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='비고')),
            ],
            options={
                'verbose_name': '도서 출고',
                'verbose_name_plural': '도서 출고 목록',
            },
        ),
        migrations.CreateModel(
            name='BookReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='반품 수량')),
                ('return_date', models.DateField(verbose_name='반품 날짜')),
            ],
            options={
                'verbose_name': '도서 반품',
                'verbose_name_plural': '도서 반품 목록',
            },
        ),
        migrations.CreateModel(
            name='BookStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='수량')),
                ('list_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='정가')),
                ('unit_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='단가')),
                ('selling_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='판매가')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('received_date', models.DateField(verbose_name='입고일')),
            ],
            options={
                'verbose_name': '도서 재고',
                'verbose_name_plural': '도서 재고',
                'ordering': ['-received_date', 'book__name'],
            },
        ),
    ]
