# Generated by Django 5.2.4 on 2026-01-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksupplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='booksupplier',
            name='phone2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호2'),
        ),
        migrations.AlterField(
            model_name='booksupplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호1'),
        ),
    ]
