# Generated by Django 5.2.4 on 2026-01-04 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
        ('subjects', '0002_subject_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='이 교재가 속한 과목', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='subjects.subject', verbose_name='과목'),
        ),
    ]
