# Generated by Django 5.2.4 on 2026-01-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_add_phone2_email_to_booksupplier'),
        ('bookstore', '0002_add_subject_to_book'),
    ]

    operations = [
    ]
