# Generated by Django 5.2.4 on 2026-01-04 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_merge_20260104_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_code',
            field=models.CharField(blank=True, help_text='ISBN 뒤 7자리 또는 자동생성 코드 (진도표 코드에 사용)', max_length=7, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='교재코드는 정확히 7자리 숫자여야 합니다.', regex='^\\d{7}$')], verbose_name='교재코드'),
        ),
    ]
