# Generated by Django 5.2.4 on 2026-01-04

from django.db import migrations


def populate_book_codes(apps, schema_editor):
    """기존 교재들에 book_code 자동 생성"""
    Book = apps.get_model('bookstore', 'Book')

    used_codes = set()
    sequence_num = 1

    for book in Book.objects.filter(book_code__isnull=True):
        book_code = None

        # ISBN에서 코드 생성 시도
        if book.isbn:
            isbn_digits = ''.join(c for c in book.isbn if c.isdigit())
            if len(isbn_digits) >= 7:
                candidate = isbn_digits[-7:]
                if candidate not in used_codes:
                    book_code = candidate
                    used_codes.add(candidate)

        # ISBN에서 생성 실패 시 순차 코드 생성
        if not book_code:
            while True:
                candidate = str(sequence_num).zfill(7)
                if candidate not in used_codes:
                    book_code = candidate
                    used_codes.add(candidate)
                    break
                sequence_num += 1

        book.book_code = book_code
        book.save(update_fields=['book_code'])


def reverse_populate(apps, schema_editor):
    """역방향 마이그레이션 - book_code를 null로"""
    Book = apps.get_model('bookstore', 'Book')
    Book.objects.update(book_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_add_book_code'),
    ]

    operations = [
        migrations.RunPython(populate_book_codes, reverse_populate),
    ]
