# Generated by Django 5.2.4 on 2026-01-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_populate_book_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksupplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booksupplier',
            name='phone2',
        ),
        migrations.AlterField(
            model_name='booksupplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='전화번호'),
        ),
    ]
