# Generated by Django 5.2.4 on 2026-01-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_remove_booksupplier_email_remove_booksupplier_phone2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_num', models.PositiveIntegerField(verbose_name='대단원 번호')),
                ('chapter_title', models.CharField(max_length=200, verbose_name='대단원 주제')),
                ('section_num', models.PositiveIntegerField(verbose_name='중단원 번호')),
                ('section_title', models.CharField(max_length=200, verbose_name='중단원 주제')),
                ('subsection_num', models.CharField(max_length=10, verbose_name='소단원 번호')),
                ('subsection_title', models.CharField(max_length=200, verbose_name='소단원 주제')),
                ('page', models.PositiveIntegerField(verbose_name='페이지')),
                ('study_date', models.DateField(blank=True, null=True, verbose_name='학습일')),
                ('achievement_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='성취 수준')),
                ('teacher_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='담당쌤')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='bookstore.book', verbose_name='교재')),
            ],
            options={
                'verbose_name': '교재 목차',
                'verbose_name_plural': '교재 목차',
                'ordering': ['book', 'page'],
                'unique_together': {('book', 'page')},
            },
        ),
    ]
