# Generated by Django 5.2.4 on 2026-01-19 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_add_book_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcontent',
            name='achievement_level',
        ),
        migrations.RemoveField(
            model_name='bookcontent',
            name='study_date',
        ),
        migrations.RemoveField(
            model_name='bookcontent',
            name='teacher_name',
        ),
    ]
