# Generated by Django 5.2.4 on 2026-01-19 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_remove_learning_fields_from_bookcontent'),
        ('teachers', '0025_add_director_assignment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(blank=True, null=True, verbose_name='학습 날짜')),
                ('achievement', models.CharField(blank=True, choices=[('', '-'), ('A', 'A (우수)'), ('B', 'B (양호)'), ('C', 'C (보통)'), ('D', 'D (미흡)'), ('F', 'F (재학습)')], default='', max_length=1, verbose_name='성취 수준')),
                ('needs_review', models.BooleanField(default=False, verbose_name='보완 추천 여부')),
                ('homework_done', models.BooleanField(default=False, verbose_name='과제 수행 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('book_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='bookstore.bookcontent', verbose_name='목차 항목')),
                ('book_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='bookstore.booksale', verbose_name='교재 지급')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='담당쌤')),
            ],
            options={
                'verbose_name': '학생 진도 기록',
                'verbose_name_plural': '학생 진도 기록',
                'ordering': ['book_sale', 'book_content__page'],
                'unique_together': {('book_sale', 'book_content')},
            },
        ),
    ]
