# Generated by Django 5.2.4 on 2026-03-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_add_student_book_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksale',
            name='is_learning_completed',
            field=models.BooleanField(default=False, verbose_name='학습 완료'),
        ),
    ]
