# Generated by Django 5.2.4 on 2026-03-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_add_is_learning_completed_to_booksale'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('kjt', '결제선생'), ('daon', '다온카드'), ('card', '신용카드'), ('transfer', '계좌이체'), ('cash', '현금'), ('other', '기타')], max_length=10, null=True, verbose_name='결제 수단'),
        ),
    ]
