# Generated by Django 5.1 on 2024-10-13 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone', models.CharField(max_length=15, verbose_name='전화번호')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1, verbose_name='성별')),
                ('hire_date', models.DateField(verbose_name='입사일')),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('id_number', models.CharField(max_length=14, verbose_name='주민번호')),
                ('account_number', models.CharField(max_length=20, verbose_name='급여 계좌')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.bank', verbose_name='거래은행')),
            ],
            options={
                'verbose_name': '교사',
                'verbose_name_plural': '교사',
            },
        ),
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='급여 월')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='급여 금액')),
                ('paid_date', models.DateField(verbose_name='지급일')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='교사')),
            ],
            options={
                'verbose_name': '교사 급여',
                'verbose_name_plural': '교사 급여',
                'unique_together': {('teacher', 'month')},
            },
        ),
    ]
