# Generated by Django 5.1 on 2024-10-13 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_purchaselocation_business_number_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='급여 계좌'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.bank', verbose_name='거래은행'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남'), ('F', '여')], max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='입사일'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='주민번호'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='급여 금액'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='month',
            field=models.DateField(blank=True, null=True, verbose_name='급여 월'),
        ),
        migrations.AlterField(
            model_name='teachersalary',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='지급일'),
        ),
    ]
