# Generated by Django 5.1 on 2024-10-13 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_account_number_alter_teacher_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='형식: YYYY-MM', max_length=7, verbose_name='급여 년월')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='기본급')),
                ('overtime_pay', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='초과 근무 수당')),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='보너스')),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='공제액')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='지급일')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='교사')),
            ],
            options={
                'verbose_name': '월별 급여',
                'verbose_name_plural': '월별 급여',
                'unique_together': {('teacher', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='YearlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='년도')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='연간 총 급여')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='교사')),
            ],
            options={
                'verbose_name': '연간 급여 총합',
                'verbose_name_plural': '연간 급여 총합',
                'unique_together': {('teacher', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='TeacherSalary',
        ),
    ]
