# Generated by Django 5.1 on 2024-10-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_rename_phone_teacher_phone_number_monthlysalary_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearlySalary',
        ),
    ]
