# Generated by Django 5.1 on 2024-10-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_delete_yearlysalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='year_month',
            field=models.DateField(verbose_name='급여 년월'),
        ),
    ]
