# Generated by Django 5.1 on 2024-10-13 23:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_monthlysalary_year_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='보너스'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='공제액'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='초과 근무 수당'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='주민번호(암호화됨)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="전화번호는 '000-0000-0000' 형식이어야 합니다.", regex='^\\d{3}-\\d{3,4}-\\d{4}$')], verbose_name='전화번호'),
        ),
    ]
