# Generated by Django 5.1 on 2024-10-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_monthlysalary_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='기본급'),
        ),
    ]
