# Generated by Django 5.1 on 2024-10-14 03:20

import django.db.models.deletion
import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_monthlysalary_base_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id_number',
        ),
        migrations.AddField(
            model_name='teacher',
            name='additional_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='추가 급여'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='base_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='급여기준'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='extra_field1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='예비1'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='extra_field2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='예비2'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='extra_field3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='예비3'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='extra_field4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='예비4'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='other_info',
            field=models.TextField(blank=True, null=True, verbose_name='기타'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='급여계좌번호'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[teachers.models.phone_number_validator], verbose_name='전화번호'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('check_in', models.TimeField(verbose_name='출근시간')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='퇴근시간')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='교사')),
            ],
            options={
                'verbose_name': '출근기록',
                'verbose_name_plural': '출근기록',
                'unique_together': {('teacher', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='년도')),
                ('month', models.IntegerField(verbose_name='월')),
                ('work_days', models.IntegerField(verbose_name='근무일수')),
                ('base_amount', models.IntegerField(verbose_name='기본급')),
                ('additional_amount', models.IntegerField(verbose_name='추가급')),
                ('total_amount', models.IntegerField(verbose_name='총액')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='교사')),
            ],
            options={
                'verbose_name': '급여',
                'verbose_name_plural': '급여',
                'unique_together': {('teacher', 'year', 'month')},
            },
        ),
        migrations.DeleteModel(
            name='MonthlySalary',
        ),
    ]
