# Generated by Django 5.1 on 2024-10-14 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_remove_teacher_id_number_teacher_additional_salary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '교사', 'verbose_name_plural': '교사들'},
        ),
        migrations.AlterField(
            model_name='salary',
            name='additional_amount',
            field=models.PositiveIntegerField(verbose_name='추가급'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_amount',
            field=models.PositiveIntegerField(verbose_name='기본급'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='월'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='total_amount',
            field=models.PositiveIntegerField(verbose_name='총액'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='year',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='년도'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='급여 계좌 번호'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='base_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='급여 기준'),
        ),
    ]
