# Generated by Django 5.1 on 2024-10-14 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_teacher_options_alter_salary_additional_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '교사', 'verbose_name_plural': '교사'},
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='월'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='work_days',
            field=models.PositiveIntegerField(verbose_name='근무일수'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='년도'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='급여계좌'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='additional_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='추가급여'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='base_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='급여기준'),
        ),
    ]
