# Generated by Django 5.1 on 2024-10-14 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_alter_teacher_options_alter_salary_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': '출근기록', 'verbose_name_plural': '출근기록들'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='출근 시간'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='퇴근 시간'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='additional_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='추가급'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_amount',
            field=models.PositiveIntegerField(default=15000, verbose_name='기본급'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='additional_salary',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='추가급여'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='base_salary',
            field=models.IntegerField(blank=True, default=15000, null=True, verbose_name='급여기준'),
        ),
    ]
