# Generated by Django 5.1 on 2024-10-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_alter_attendance_options_remove_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': '출근기록', 'verbose_name_plural': '출근기록들'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='근무 종료 시간'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='근무 시작 시간'),
        ),
    ]
