# Generated by Django 5.1 on 2024-10-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_alter_teacher_hire_date_alter_teacher_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': '출근기록', 'verbose_name_plural': '출근기록'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='입사일'),
        ),
    ]
