# Generated by Django 5.1.4 on 2024-12-08 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_alter_salary_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='월'),
        ),
    ]
