# Generated by Django 5.2.4 on 2025-12-03 02:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0019_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='additional_salary',
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='월'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='전화번호는 9-11자리 숫자로 입력해주세요. (예: 01012345678, 0212345678)', regex='^\\d{9,11}$')], verbose_name='전화번호'),
        ),
    ]
