# Generated by Django 5.2.4 on 2026-01-02 00:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0020_remove_teacher_additional_salary_alter_salary_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='월'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='year',
            field=models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='년도'),
        ),
    ]
