# Generated by Django 5.2.4 on 2026-01-09 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_alter_salary_month_alter_salary_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('reason', models.CharField(choices=[('personal', '개인 사유'), ('sick', '병가'), ('vacation', '휴가'), ('other', '기타')], default='personal', max_length=20, verbose_name='사유')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='교사')),
            ],
            options={
                'verbose_name': '출근 불가 일정',
                'verbose_name_plural': '출근 불가 일정',
                'ordering': ['date', 'teacher__name'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
