# Generated by Django 5.2.4 on 2026-01-09 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_unpaid_amount'),
        ('teachers', '0022_teacherunavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='학생')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='교사')),
            ],
            options={
                'verbose_name': '교사-학생 배정',
                'verbose_name_plural': '교사-학생 배정',
                'ordering': ['date', 'teacher__name', 'student__name'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
