# Generated by Django 5.2.4 on 2026-01-17 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0023_teacherstudentassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudentassignment',
            name='assignment_type',
            field=models.CharField(choices=[('normal', '일반'), ('absent', '결석'), ('exception', '예외')], default='normal', max_length=10, verbose_name='배정 유형'),
        ),
        migrations.AlterField(
            model_name='teacherstudentassignment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='교사'),
        ),
    ]
