# Generated by Django 5.2.4 on 2026-01-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0024_add_assignment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudentassignment',
            name='assignment_type',
            field=models.CharField(choices=[('normal', '일반'), ('director', '원장'), ('absent', '결석'), ('exception', '예외')], default='normal', max_length=10, verbose_name='배정 유형'),
        ),
    ]
