# Generated by Django 5.2.4 on 2026-01-22 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_director_memo'),
        ('teachers', '0026_add_user_to_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('instruction', '지시사항'), ('reply', '답변'), ('notice', '공지')], default='instruction', max_length=20, verbose_name='메시지 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='teachers.message', verbose_name='원본 메시지')),
                ('recipient', models.ForeignKey(blank=True, help_text='비워두면 전체 공지', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='받는 사람')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='보낸 사람')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='students.student', verbose_name='관련 학생')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지',
                'ordering': ['-created_at'],
            },
        ),
    ]
