# Generated by Django 5.2.4 on 2026-01-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0028_add_message_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereadstatus',
            name='dismissed',
            field=models.BooleanField(default=False, verbose_name='알림 닫음'),
        ),
    ]
