# Generated by Django 5.2.4 on 2026-01-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0029_add_dismissed_to_messagereadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailabilityBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='차단 날짜')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='차단 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '출근 불가 차단 날짜',
                'verbose_name_plural': '출근 불가 차단 날짜',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='UnavailabilitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_unavailability_per_month', models.PositiveIntegerField(default=5, verbose_name='월간 최대 등록 가능 일수')),
                ('require_approval', models.BooleanField(default=True, verbose_name='교사 등록 시 승인 필요')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '출근 불가 일정 설정',
                'verbose_name_plural': '출근 불가 일정 설정',
            },
        ),
        migrations.AddField(
            model_name='teacherunavailability',
            name='created_by_admin',
            field=models.BooleanField(default=True, verbose_name='관리자 등록 여부'),
        ),
        migrations.AddField(
            model_name='teacherunavailability',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='반려 사유'),
        ),
        migrations.AddField(
            model_name='teacherunavailability',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검토일시'),
        ),
        migrations.AddField(
            model_name='teacherunavailability',
            name='status',
            field=models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '반려됨')], default='approved', max_length=20, verbose_name='승인 상태'),
        ),
    ]
