# Generated by Django 5.2.4 on 2026-01-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0030_add_unavailability_approval_and_settings'),
    ]

    operations = [
        # Teacher 모델에 개별 월간 제한 필드 추가
        migrations.AddField(
            model_name='teacher',
            name='max_unavailability_per_month',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='비워두면 제한 없음',
                null=True,
                verbose_name='월간 출근 불가 제한'
            ),
        ),
        # UnavailabilitySettings에서 불필요한 필드 제거
        migrations.RemoveField(
            model_name='unavailabilitysettings',
            name='max_unavailability_per_month',
        ),
        migrations.RemoveField(
            model_name='unavailabilitysettings',
            name='require_approval',
        ),
    ]
