# Generated by Django 5.2.10 on 2026-01-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0031_teacher_max_unavailability_per_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherunavailability',
            name='reject_notified',
            field=models.BooleanField(default=False, verbose_name='반려 알림 확인'),
        ),
    ]
