# Generated by Django 5.2.10 on 2026-02-01 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0032_add_reject_notified_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='월'),
        ),
    ]
