# Generated by Django 5.2.4 on 2026-02-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0033_alter_salary_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudentassignment',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('', '-'), ('sick', '아파서'), ('family', '가족 모임'), ('personal', '개인 일정'), ('other', '기타')], default='', max_length=20, verbose_name='결석 사유'),
        ),
    ]
