# Generated by Django 5.2.4 on 2026-03-26 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0034_add_absence_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='월'),
        ),
    ]
