# Generated by Django 5.2.4 on 2026-03-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0035_alter_salary_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='지급일자'),
        ),
    ]
