"""
Django settings for mclass_manager project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# .env 파일 로드 (로컬 개발 환경용, Docker에서는 환경변수 직접 사용)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv가 없으면 환경변수 직접 사용

try:
    import mclass_settings
except ImportError:
    mclass_settings = None


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# 폰트 파일 경로
FONT_PATH = os.path.join(BASE_DIR, 'NanumGothic.ttf')

# 미디어 파일 설정
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', mclass_settings.SECRET_KEY if mclass_settings else 'django-insecure-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF 신뢰 도메인 (Django 4.0+에서 필수)
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in
    os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost,http://127.0.0.1').split(',')
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'import_export',
    'django_summernote',
    'common',
    'teachers',
    'students',
    'bookstore',
    'subjects',
    'grades',
    'maintenance',
    'progress',
    'homepage',
    'classes',
]


# Crispy Forms 설정
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = "bootstrap4"

# Summernote 설정
SUMMERNOTE_THEME = 'lite'  # Bootstrap 의존성 없는 경량 버전
SUMMERNOTE_CONFIG = {
    'iframe': False,
    'summernote': {
        'width': '100%',
        'height': 400,
        'lang': 'ko-KR',
        'toolbar': [
            ['style',  ['style']],
            ['font',   ['bold', 'underline', 'italic', 'strikethrough', 'clear']],
            ['fontsize', ['fontsize']],
            ['color',  ['color']],
            ['para',   ['ul', 'ol', 'paragraph']],
            ['table',  ['table']],
            ['insert', ['link', 'picture', 'hr']],
            ['view',   ['fullscreen', 'codeview']],
        ],
    },
    'attachment_require_authentication': True,
    'attachment_filesize_limit': 5 * 1024 * 1024,  # 5MB
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'mclass_manager.middleware.SubdomainRoutingMiddleware',  # 서브도메인 라우팅 (최상단)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mclass_manager.middleware.TeacherAccessRestrictionMiddleware',  # 교사 접근 제한
]

ROOT_URLCONF = 'mclass_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'teachers.context_processors.teacher_notices',
                'homepage.context_processors.consultation_count',
                'homepage.context_processors.visitor_counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'mclass_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'mclass_manager_db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', mclass_settings.db_password if mclass_settings else ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'; SET CHARACTER SET utf8mb4; SET collation_connection = 'utf8mb4_general_ci';",
        }
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 로그아웃 후 리다이렉트할 URL
LOGOUT_REDIRECT_URL = 'login'

# 로그인 URL (로그인이 필요한 페이지 접근 시 리다이렉트)
LOGIN_URL = 'login'

# 로그인 후 리다이렉트할 URL
LOGIN_REDIRECT_URL = 'index'



# data logging
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'security.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {  # 루트 로거
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# Aligo SMS API 설정
# 환경변수 또는 mclass_settings 모듈에서 가져옴
SMS_API_KEY = os.environ.get('SMS_API_KEY', getattr(mclass_settings, 'SMS_API_KEY', None) if mclass_settings else None)
SMS_USER_ID = os.environ.get('SMS_USER_ID', getattr(mclass_settings, 'SMS_USER_ID', None) if mclass_settings else None)
SMS_SENDER_NUMBER = os.environ.get('SMS_SENDER_NUMBER', getattr(mclass_settings, 'SMS_SENDER_NUMBER', None) if mclass_settings else None)

# 카카오 도서 검색 API (ISBN 조회 보완용 - 국립중앙도서관에 없는 참고서/문제집 대비)
KAKAO_REST_API_KEY = os.environ.get('KAKAO_REST_API_KEY', getattr(mclass_settings, 'KAKAO_REST_API_KEY', '') if mclass_settings else '')

# Email 설정
# 개발 환경에서는 console backend 사용 (실제 이메일 발송 안 함)
# 프로덕션에서는 SMTP 설정 필요
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')  # 예: 'smtp.gmail.com'
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'jjangdm@mclass.co.kr')

# 관리자 알림 수신 번호 (.env에서 설정 — 예: 010-1234-5678)
ADMIN_PHONE = os.environ.get('ADMIN_PHONE', '')


# ============================================
# 보안 설정 (Security Settings)
# ============================================

# X-Frame-Options: Clickjacking 방지
X_FRAME_OPTIONS = 'DENY'

# Content-Type 스니핑 방지
SECURE_CONTENT_TYPE_NOSNIFF = True

# XSS 필터 활성화
SECURE_BROWSER_XSS_FILTER = True

# 프로덕션 환경 보안 설정 (DEBUG=False일 때만 적용)
if not DEBUG:
    # HTTPS 강제 리다이렉트 (SSL 설정 전에는 False로 설정)
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'

    # 프록시 뒤에서 HTTPS 감지
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HSTS (HTTP Strict Transport Security) 설정
    SECURE_HSTS_SECONDS = 31536000  # 1년
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # 쿠키 보안 설정 (HTTPS 환경에서만 True로 설정)
    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True') == 'True'
    CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True') == 'True'

    # SameSite 쿠키 설정 (CSRF 방지)
    SESSION_COOKIE_SAMESITE = 'Lax'  # Strict는 일부 브라우저에서 문제 발생
    CSRF_COOKIE_SAMESITE = 'Lax'

    # 세션 설정
    SESSION_COOKIE_AGE = 3600 * 8  # 8시간
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# ============================================
# 파일 업로드 보안 설정
# ============================================

# 허용된 파일 확장자
ALLOWED_UPLOAD_EXTENSIONS = {
    'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx',
    'jpg', 'jpeg', 'png', 'gif', 'bmp',
    'txt', 'csv', 'hwp', 'zip'
}

# 허용된 MIME 타입
ALLOWED_UPLOAD_MIME_TYPES = {
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/bmp',
    'text/plain',
    'text/csv',
    'application/x-hwp',
    'application/zip',
}

# 최대 파일 크기 (10MB)
MAX_UPLOAD_SIZE = 10 * 1024 * 1024

# Excel/CSV 가져오기용 최대 파일 크기 (5MB)
MAX_IMPORT_FILE_SIZE = 5 * 1024 * 1024


# ============================================
# Google Drive API 설정
# ============================================

# 서비스 계정 JSON 키 파일 경로
GOOGLE_SERVICE_ACCOUNT_FILE = os.environ.get(
    'GOOGLE_SERVICE_ACCOUNT_FILE',
    os.path.join(BASE_DIR, 'credentials', 'google_service_account.json')
)

# Google Drive API 스코프
GOOGLE_DRIVE_SCOPES = [
    'https://www.googleapis.com/auth/drive',
    'https://www.googleapis.com/auth/drive.file',
]

# Google Drive 루트 폴더 ID (MClass 전용 폴더)
# 설정하지 않으면 서비스 계정의 드라이브 루트에 생성됨
GOOGLE_DRIVE_ROOT_FOLDER_ID = os.environ.get('GOOGLE_DRIVE_ROOT_FOLDER_ID', '')

# 도메인 전체 위임 사용 시 위임할 사용자 이메일
GOOGLE_DELEGATED_USER_EMAIL = os.environ.get('GOOGLE_DELEGATED_USER_EMAIL', '')

# 소유자 권한 문제(예: 개인 계정으로 직접 업로드한 파일)로 삭제가 실패할 경우
# 재시도할 위임 계정 (기본 서비스 계정에 삭제 권한이 없을 때의 폴백)
GOOGLE_DRIVE_OWNER_EMAIL = os.environ.get('GOOGLE_DRIVE_OWNER_EMAIL', 'jjangdm@mclass.co.kr')

