# Generated by Django 5.2.4 on 2026-03-08 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('source_url', models.URLField(blank=True, verbose_name='스크래핑 URL')),
                ('source_name', models.CharField(blank=True, max_length=100, verbose_name='출처명')),
                ('original_url', models.URLField(blank=True, verbose_name='원문 링크')),
                ('is_published', models.BooleanField(default=True, verbose_name='게시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '입시뉴스',
                'verbose_name_plural': '입시뉴스',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(default='엠클래스 수학과학전문학원', max_length=100, verbose_name='학원명')),
                ('subtitle', models.CharField(default='수학·과학 전문 학원', max_length=200, verbose_name='슬로건')),
                ('intro_text', models.TextField(default='', verbose_name='학원 소개')),
                ('vision_text', models.TextField(default='', verbose_name='교육 철학')),
                ('address', models.CharField(default='', max_length=300, verbose_name='주소')),
                ('phone', models.CharField(default='031-439-1222', max_length=20, verbose_name='전화번호')),
                ('email', models.EmailField(default='jjangdm@mclass.co.kr', max_length=254, verbose_name='이메일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '학원소개',
                'verbose_name_plural': '학원소개',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_published', models.BooleanField(default=True, verbose_name='게시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '원장칼럼',
                'verbose_name_plural': '원장칼럼',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('is_published', models.BooleanField(default=True, verbose_name='게시 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-created_at'],
            },
        ),
    ]
