# Generated by Django 5.2.4 on 2026-03-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1, verbose_name='성별')),
                ('school', models.CharField(max_length=100, verbose_name='학교')),
                ('grade', models.CharField(choices=[('K5', '초5'), ('K6', '초6'), ('K7', '중1'), ('K8', '중2'), ('K9', '중3'), ('K10', '고1'), ('K11', '고2'), ('K12', '고3')], max_length=3, verbose_name='학년')),
                ('phone_number', models.CharField(max_length=20, verbose_name='학생 전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='부모님 전화번호')),
                ('subjects', models.CharField(blank=True, max_length=300, verbose_name='상담 과목')),
                ('learning_methods', models.CharField(blank=True, max_length=200, verbose_name='기존 학습 방법')),
                ('current_status', models.TextField(blank=True, verbose_name='현재 학습 상황')),
                ('current_textbook', models.CharField(blank=True, max_length=200, verbose_name='학습 중인 교재')),
                ('last_score', models.IntegerField(blank=True, null=True, verbose_name='직전 학기 점수')),
                ('expectation', models.TextField(blank=True, verbose_name='학원에 바라는 점')),
                ('status', models.CharField(choices=[('new', '신규'), ('contacted', '연락 완료'), ('registered', '등록 완료')], default='new', max_length=20, verbose_name='처리 상태')),
                ('admin_memo', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
            ],
            options={
                'verbose_name': '상담 신청',
                'verbose_name_plural': '상담 신청',
                'ordering': ['-created_at'],
            },
        ),
    ]
