# Generated by Django 5.2.4 on 2026-03-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_add_consultation_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='일일 방문자 수')),
            ],
            options={
                'verbose_name': '방문자 통계',
                'verbose_name_plural': '방문자 통계',
                'ordering': ['-date'],
            },
        ),
    ]
