# Generated by Django 5.1 on 2024-10-24 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(help_text='양수만 입력 가능합니다.', validators=[django.core.validators.MinValueValidator(1, message='호실 번호는 양수여야 합니다.')], verbose_name='호실')),
                ('date', models.DateField(help_text='년월을 선택해주세요 (예: 2024년 10월)', verbose_name='부과년월')),
                ('charge', models.IntegerField(help_text='0 이상의 금액을 입력해주세요.', validators=[django.core.validators.MinValueValidator(0, message='금액은 0 이상이어야 합니다.')], verbose_name='부과금액')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='납부일자')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '관리비',
                'verbose_name_plural': '관리비 목록',
                'ordering': ['-date', 'room'],
            },
        ),
    ]
