# Generated by Django 5.1 on 2024-10-24 02:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='양수만 입력 가능합니다.', unique=True, validators=[django.core.validators.MinValueValidator(1, message='호실 번호는 양수여야 합니다.')], verbose_name='호실')),
                ('contract_start_date', models.DateField(verbose_name='계약 시작일')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='계약 종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='계약 활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '호실 정보',
                'verbose_name_plural': '호실 목록',
                'ordering': ['number'],
            },
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.room', verbose_name='호실'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['room'], name='maintenance_room_id_681cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['date'], name='maintenance_date_be465d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['date_paid'], name='maintenance_date_pa_52f6be_idx'),
        ),
    ]
