# Generated by Django 5.1 on 2024-10-24 02:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_room_alter_maintenance_room_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='maintenance',
            name='maintenance_room_id_681cd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenance',
            name='maintenance_date_be465d_idx',
        ),
        migrations.RemoveIndex(
            model_name='maintenance',
            name='maintenance_date_pa_52f6be_idx',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='room',
            field=models.IntegerField(help_text='양수만 입력 가능합니다.', validators=[django.core.validators.MinValueValidator(1, message='호실 번호는 양수여야 합니다.')], verbose_name='호실'),
        ),
    ]
