# Generated by Django 5.2.4 on 2026-03-24 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='rent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='금액은 0 이상이어야 합니다.')], verbose_name='임차료'),
        ),
    ]
