# Generated by Django 5.2.4 on 2025-12-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(help_text='고유 과목 코드 (예: 1001, 2001)', max_length=10, unique=True, verbose_name='과목코드')),
                ('name', models.CharField(max_length=100, verbose_name='과목명')),
                ('special_code', models.CharField(blank=True, help_text='특수 분류 코드', max_length=50, null=True, verbose_name='특수코드')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('extra', models.CharField(blank=True, help_text='추가 정보', max_length=200, null=True, verbose_name='여분')),
                ('is_active', models.BooleanField(default=True, help_text='현재 교육과정에서 사용 중인 과목', verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '과목',
                'verbose_name_plural': '과목 목록',
                'db_table': 'subjects',
                'ordering': ['subject_code'],
            },
        ),
    ]
