# Generated by Django 5.2.4 on 2025-12-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category_code',
            field=models.CharField(blank=True, help_text='교과 분류 코드 (예: 10, 20, 91, 92, 93)', max_length=2, null=True, verbose_name='교과코드'),
        ),
    ]
