# Generated by Django 5.2.4 on 2026-03-20 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='curriculum_year',
            field=models.IntegerField(choices=[(2015, '2015 개정'), (2022, '2022 개정')], default=2015, help_text='2015 개정 또는 2022 개정 교육과정', verbose_name='교육과정'),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisite',
            field=models.ForeignKey(blank=True, help_text='이 과목의 선수과목 (공통과목이 선택과목의 선수과목이 되는 경우)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_subjects', to='subjects.subject', verbose_name='선수과목'),
        ),
    ]
