# Generated by Django 5.2.4 on 2026-03-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_add_curriculum_year_and_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school_level',
            field=models.CharField(choices=[('M', '중학교'), ('H', '고등학교')], default='H', help_text='M=중학교, H=고등학교', max_length=1, verbose_name='학교급'),
        ),
    ]
